name: Daily Scrape

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours at minute 0
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v4
        name: "Install pnpm"
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run scraper
        env:
          SMARTWATER_USERNAME: ${{ secrets.SMARTWATER_USERNAME }}
          SMARTWATER_PASSWORD: ${{ secrets.SMARTWATER_PASSWORD }}
          SMARTWATER_API_KEY: ${{ secrets.SMARTWATER_API_KEY }}
        run: npm run scrape

      - uses: stefanzweifel/git-auto-commit-action@v5
        name: "Commit and push"
        with:
          commit_message: Automated tanks.db update
